name: Java CI Workflow

on:
  push: # O workflow será acionado quando um push qualquer for feito.
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Executar testes
      run: |
        ./gradlew test # ou 'mvn test', dependendo do gerenciador de build
