name: Java Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Etapa 1: Fazer o checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Etapa 2: Configurar o Java
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'

      # Etapa 3: Construir o projeto com Maven
      - name: Build with Maven
        run: mvn clean package

      # Etapa 4: Executar os testes
      - name: Run tests
        run: mvn test
